throw_exception
rethrow_exception
